# v0.1 release candidate
name: compositionspace_iuc09
channels:
  - conda-forge
dependencies:
  - numpy
  - h5py
  - scikit-learn
  - pyyaml
  - flatdict
  - lxml
  - ifes-apt-tc-data-modeling>=0.2.1
  - trimesh
  # - matplotlib
  # - pytest
  # - pandas
  # - numba
  # - tqdm
  # - pyevtk
  # - ipywidgets
  # - ipyvtklink
  # - pyvista
  # - ipywidgets
  # - panel